server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: expectedCases
  data:
    mongodb:
      uri: mongodb://localhost:27017/expectedCases
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    topic:
      expectedCases-customer: expectedCases.customer.change
    consumer:
      group-id: expectedCases
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
---
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://mongo:27017/expectedCases
  kafka:
    bootstrap-servers: kafka:9092
logging:
  level:
    root: INFO
